### ISSUE TITLE
Simplify code somewhat

### ISSUE THREAD

**Issue by bangerth** [juleoc02/SAND#4]
You have this code in your `run()` function:
```
      setup_block_system ();
      set_bcids ();

      int num_iterations = 1000;

      for (int j = 0; j < num_iterations;)
        {
          bool convergence_reached = false;
          while ((convergence_reached == false) && (j < num_iterations))
            {
              re_setup_block_system ();
```
If you follow the control flow here, then this includes calling `setup_block_system()`, entering the loop, and calling `re_setup_block_system()` where you duplicate some of the work done in `setup_block_system()`. Since you call `re_setup...()` at the beginning of each iteration, you don't actually need to do that part of the functionality that's in `re_setup...()` in `setup_...()`. 

In the abstract, you could have also avoided the code duplication by letting `setup_...()` call `re_setup_...()` at the end. Because that sounds funny, this also suggests that maybe `re_setup_...()` isn't actually the best name. I *suspect*, but don't really know, that what you want this function to do is to zero out the solution and rhs vectors? What you're doing here is one way to achieve this, but in reality both of these vectors already have the correct size (and so don't have to be resized again) and just saying `solution = 0` and `system_rhs = 0` would have achieved the same.

**Comment by juleoc02** [comment]
I've thought of putting the "re-setup" function at the end, because it does look funny. But I also thought that for every step but the first one, it is kinda the first thing that happens in an iteration, so I felt having it at the beginning of the loop showed what each iteration did better.
Would "reset_block_system" make more sense? Not doing setup, but resetting it to the 0 values is really what it's doing. Or, I could realistically just make the assemble step start by making these things zero before adding values to them, (which I like a lot now that I'm writing it down)
Also, the setting vectors to 0 thing is definitely something I've seen I can do before, and I just forgot.

I'm going to move this whole function into the assemble system bit, because that takes care of putting the right values in the right place.

**Comment by bangerth** [comment]
That's how all the nonlinear and time dependent programs do it: They reset the matrix and rhs to zero at the beginning of `assemble_system()`. That's conceptually also where it belongs: you're forming a linear system by adding up contributions from all cells; starting at zero seems like the right thing to do as part of the function that does the summation.
